This package contains python-django.el

* Info

  + Author: Fabián Ezequiel Gallina
  + Contact: fabian at anue dot biz
  + Project homepage: http://github.com/fgallina/python-django.el
  + My Blog: http://www.from-the-cloud.com
  + Downloads page: http://github.com/fgallina/python.el/downloads

* Introduction

  A Jazzy package for managing Django projects.

  Django project management package with the goodies you would expect
  and then some.  The project buffer workings is pretty much inspired
  by the good ol' `magit-status' buffer.

  See the header of python-django.el for more information.

* Requirements

  This package relies heavily in fgallina's `python.el' available in
  stock Emacs>=24.3 (or https://github.com/fgallina/python.el).

* Installation/Usage

  Add this to your .emacs:

  #+BEGIN_EXAMPLE
  (add-to-list 'load-path "/folder/containing/file")
  (require 'python-django)
  #+END_EXAMPLE

  See this blog post for a detailed quick start:
  http://from-the-cloud.com/en/emacs/2013/01/28_emacs-as-a-django-ide-with-python-djangoel.html

* Bug Reports

  If you find a bug please report it in the github tracker.

* License

  python-django.el is free software under the GPL v3, see LICENSE file
  for details.
